name: Dividendos IBKR Daily

on:
  schedule:
    # Ejecutar todos los días a las 09:00 UTC (ajusta según tu zona horaria)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Permite ejecución manual

jobs:
  run-dividendos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run dividendos script
      env:
        IBKR_FLEX_TOKEN: ${{ secrets.IBKR_FLEX_TOKEN }}
        IBKR_DIVIDENDS_QUERY_ID: ${{ secrets.IBKR_DIVIDENDS_QUERY_ID }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        IBKR_USERNAME: ${{ secrets.IBKR_USERNAME }}
        IBKR_PASSWORD: ${{ secrets.IBKR_PASSWORD }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        # Añade más variables según necesites
      run: |
        python main.py
        
    - name: Upload logs (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dividendos-logs
        path: |
          *.log
          *.txt
        retention-days: 7
